apiVersion: v1
kind: Pod
metadata:
  name: cm-nginx
  labels:
    app: nginx
spec:
  volumes:
  - name: myvol
    configMap:
      name: myfile
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Service
metadata:
  name: cm-nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30124

