apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-node
spec:
   selector:
     matchLabels:
      app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       nodeSelector:
         cpu: ryzen
       containers:
       - name: con1
         image: nginx:latest
         ports:
         - containerPort: 80
