apiVersion: v1
kind: LimitRange
metadata:
  name: lr-jenkins
  namespace: jenkins
spec:
  limits:
  - default: # this section defines default limits
      cpu: "500m"
      memory: "512Mi"
    defaultRequest: # this section defines default requests
      cpu: "100m"
      memory: "64Mi"
    type: Container
