apiVersion: v1
kind: Pod
metadata:
  name: mpod-exec
  labels:
    app: mypod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
          - cat
          - /etc/hosts
      initialDelaySeconds: 7
      periodSeconds: 5
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
  selector:
    app: mypod
  ports:
  - port: 80
