apiVersion: v1
kind: Pod
metadata:
  name: mpod
  labels:
    app: mypod
    env: dev
    appgroup: mango
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080

