apiVersion: v1
kind: ConfigMap
metadata:
  name: myconf
data:
  WORDPRESS_DB_HOST: wordpress
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: test123
  WORDPRESS_DB_USER: root
  WORDPRESS_TABLE_PREFIX: wp_
