apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mydb
spec:
  containers:
  - name: con2
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mydb
  ports:
  - port: 3306 
    protocol: TCP
    targetPort: 3306

