apiVersion: v1
kind: Pod
metadata:
  name: mypod-ns
  labels:
    app: mypod
spec:
  containers:
  - name: con1
    image: tomcat:latest
    ports:
    - containerPort: 8080
  nodeSelector:
    cpu: ryzen

