apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: test
spec:
  containers:
  - name: con1
    image: tomcat:latest
    ports:
    - containerPort: 8080
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - myapp
          topologyKey: kubernetes.io/hostname  
