apiVersion: v1
kind: Pod
metadata:
  name: mypod-pref
  labels:
    app: mypod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
     nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
           matchExpressions:
           - key: cpu
             operator: NotIn  #anti affinity operator 
             values:
             - ryzen          
