apiVersion: v1
kind: Pod
metadata:
  name: req-aff
  labels:
    app: mypod
spec:
  containers:
  - name: con1
    image: tomcat:latest
    ports:
    - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: NotIn
            values:
            - ryzen         
