apiVersion: v1
kind: Pod
metadata:
  name: mpod-res
  labels:
    app: mypod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:   #min resource
        cpu: "250m"
        memory: "64Mi"
      limits:     #max resources
        cpu: "500m"
        memory: "128Mi"
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080
    resources:
      requests:   #min resource
        cpu: "250m"
        memory: "64Mi"
      limits:     #max resources
        cpu: "500m"
        memory: "128Mi"

