apiVersion: v1
kind: Pod
metadata:
  name: apple
  namespace: jenkins
  labels:
    app: myapp
spec:
  serviceAccount: mango
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:   #min resource
        cpu: "250m"
        memory: "128Mi"
      limits:     #max resources
        cpu: "500m"
        memory: "1Gi"

