apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
  type: NodePort
  selector:
    app: mypod
    appgroup: mango
    env: dev
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
