apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  volumes:
  - name: myvol
    secret:
      secretName: mycert
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      valueFrom:
        configMapKeyRef: 
          name: myconf
          key: WORDPRESS_DB_HOST  
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: test123
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_TABLE_PREFIX
      value: wp_
    volumeMounts:
    - name: myvol
      mountPath: /data
  - name: con2
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypass
          key: pass   
    - name: MYSQL_DATABASE
      value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30124

